### ISSUE TITLE
Gone from the Store

### ISSUE THREAD

**Issue by hcbille** [isiah-lloyd/VolumeMixer-decky#1]
Hi!

I just found this plugin but cannot find it in the store, is there any plans to add it?

**Comment by isiah-lloyd** [comment]
Hey there. It was in the store, but I've decided to remove my plugins from the store due to having to keep up with Steam OS updates that would break the plugin and the stress of trying to get updates approved. I have just put out a release on Github that you can manually add to your Deck here: https://github.com/isiah-lloyd/VolumeMixer-decky/releases/tag/1.1.0
